{{Subsuperscript["N", 1, 4], Superscript["S", 1], "I", Subscript["C", 2], 
  Superscript["Z", 3] \[CirclePlus] Subscript["Z", 2], Subscript["C", 2], 
  Subsuperscript["O", 1, 4], "2/1/1/2"}, {Subsuperscript["N", 2, 4], 
  Superscript["S", 1], "I", Subsuperscript["C", 2, 2], Superscript["Z", 3], 
  Subscript["C", 2], Subsuperscript["O", 1, 4], "2/1/2/2"}, 
 {Subsuperscript["N", 3, 4], Superscript["T", 2], "*2222", 
  Subsuperscript["C", 2, 2], Superscript["Z", 2] \[CirclePlus] 
   Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 2], 
  Subsuperscript["O", 2, 4], "4/1/1/10"}, {Subsuperscript["N", 4, 4], 
  Superscript["T", 2], "22*", Subsuperscript["C", 2, 2], 
  Superscript["Z", 2] \[CirclePlus] Subscript["Z", 2], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], "4/1/1/11"}, 
 {Subsuperscript["N", 5, 4], Superscript["T", 2], "22x", 
  Subsuperscript["C", 2, 2], Superscript["Z", 2] \[CirclePlus] 
   Subscript["Z", 2], Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], 
  "4/1/1/13"}, {Subsuperscript["N", 6, 4], Superscript["T", 2], "2*22", 
  Subsuperscript["C", 2, 2], Superscript["Z", 2] \[CirclePlus] 
   Subscript["Z", 2], Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], 
  "4/1/2/4"}, {Subsuperscript["N", 7, 4], Superscript["T", 2], "22x", 
  Row[{Subscript["C", 4], "\[Times]", Subscript["C", 2]}], 
  Superscript["Z", 2], Subsuperscript["C", 2, 2], Subsuperscript["O", 3, 4], 
  "4/1/6/4"}, {Subsuperscript["N", 8, 4], Superscript["K", "2"], "22*", 
  Subscript["C", 2], Superscript["Z", 2] \[CirclePlus] 
   Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 2], 
  Subsuperscript["O", 2, 4], "4/1/1/6"}, {Subsuperscript["N", 9, 4], 
  Superscript["K", "2"], "22x", Subscript["C", 2], 
  Superscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], "4/1/1/7"}, 
 {Subsuperscript["N", 10, 4], Superscript["K", "2"], "*2222", 
  Subsuperscript["C", 2, 2], Superscript["Z", 2] \[CirclePlus] 
   Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 2], 
  Subsuperscript["O", 3, 4], "4/1/3/11"}, {Subsuperscript["N", 11, 4], 
  Superscript["K", "2"], "22*", Subsuperscript["C", 2, 2], 
  Superscript["Z", 2] \[CirclePlus] Subscript["Z", 2], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 3, 4], "4/1/3/4"}, 
 {Subsuperscript["N", 12, 4], Superscript["K", "2"], "22*", 
  Subsuperscript["C", 2, 2], Superscript["Z", 2] \[CirclePlus] 
   Subscript["Z", 2], Subsuperscript["C", 2, 2], Subsuperscript["O", 3, 4], 
  "4/1/3/12"}, {Subsuperscript["N", 13, 4], Superscript["K", "2"], "2*22", 
  Subsuperscript["C", 2, 2], Superscript["Z", 2] \[CirclePlus] 
   Subscript["Z", 2], Subsuperscript["C", 2, 2], Subsuperscript["O", 3, 4], 
  "4/1/4/5"}, {Subsuperscript["N", 14, 4], Subsuperscript["O", 1, 3], "(#2)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 3], 
  Subscript["C", 2], Subsuperscript["O", 1, 4], "2/2/1/2"}, 
 {Subsuperscript["N", 15, 4], Subsuperscript["O", 1, 3], "(#81)", 
  Subscript["C", 4], "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Subscript["C", 4], Subsuperscript["O", 2, 4], "12/1/2/2"}, 
 {Subsuperscript["N", 16, 4], Subsuperscript["O", 1, 3], "(#82)", 
  Subscript["C", 4], "Z" \[CirclePlus] Subscript["Z", 4], Subscript["C", 4], 
  Subsuperscript["O", 3, 4], "12/1/4/2"}, {Subsuperscript["N", 17, 4], 
  Subsuperscript["O", 2, 3], "(#81)", Subscript["C", 4], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subscript["C", 4], 
  Subsuperscript["O", 2, 4], "12/1/3/2"}, {Subsuperscript["N", 18, 4], 
  Subsuperscript["O", 2, 3], "(#82)", Subscript["C", 4], 
  "Z" \[CirclePlus] Subscript["Z", 4], Subscript["C", 4], 
  Subsuperscript["O", 3, 4], "12/1/6/2"}, {Subsuperscript["N", 19, 4], 
  Subsuperscript["O", 1, 3], "(#174)", Subscript["C", 6], 
  "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] Subscript["Z", 3], 
  Subscript["C", 6], Subsuperscript["O", 4, 4], "14/2/3/2"}, 
 {Subsuperscript["N", 20, 4], Subsuperscript["O", 1, 3], "(#147)", 
  Subscript["C", 6], "Z" \[CirclePlus] Subscript["Z", 2], Subscript["C", 6], 
  Subsuperscript["O", 4, 4], "14/1/3/2"}, {Subsuperscript["N", 21, 4], 
  Subsuperscript["O", 1, 3], "(#148)", Subscript["C", 6], 
  "Z" \[CirclePlus] Subscript["Z", 2], Subscript["C", 6], 
  Subsuperscript["O", 5, 4], "14/1/1/2"}, {Subsuperscript["N", 22, 4], 
  Subsuperscript["O", 2, 3], "(#11)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 3], Subsuperscript["C", 2, 2], 
  Subsuperscript["O", 2, 4], "4/2/1/8"}, {Subsuperscript["N", 23, 4], 
  Subsuperscript["O", 2, 3], "(#14)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], "4/2/1/16"}, 
 {Subsuperscript["N", 24, 4], Subsuperscript["N", 1, 3], "(#13)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 3], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], "4/2/1/11"}, 
 {Subsuperscript["N", 25, 4], Subsuperscript["N", 1, 3], "(#14)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] 
   Subscript["Z", 4], Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], 
  "4/2/1/12"}, {Subsuperscript["N", 26, 4], Subsuperscript["N", 2, 3], 
  "(#15)", Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 3, 4], "4/2/3/4"}, 
 {Subsuperscript["N", 27, 4], Subsuperscript["N", 1, 3], "(#85)", 
  Subscript["C", 4], "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Row[{Subscript["C", 2], "\[Times]", Subscript["C", 4]}], 
  Subsuperscript["O", 6, 4], "13/1/1/8"}, {Subsuperscript["N", 28, 4], 
  Subsuperscript["N", 1, 3], "(#86)", Subscript["C", 4], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Row[{Subscript["C", 2], "\[Times]", Subscript["C", 4]}], 
  Subsuperscript["O", 6, 4], "13/1/1/11"}, {Subsuperscript["N", 29, 4], 
  Subsuperscript["N", 2, 3], "(#88)", Subscript["C", 4], 
  "Z" \[CirclePlus] Subscript["Z", 2], 
  Row[{Subscript["C", 2], "\[Times]", Subscript["C", 4]}], 
  Subsuperscript["O", 7, 4], "13/1/3/8"}, {Subsuperscript["N", 30, 4], 
  Subsuperscript["N", 3, 3], "(#54)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 3], Subsuperscript["C", 2, 3], 
  Subsuperscript["O", 9, 4], "6/1/1/63"}, {Subsuperscript["N", 31, 4], 
  Subsuperscript["N", 3, 3], "(#57)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 3], Subsuperscript["C", 2, 3], 
  Subsuperscript["O", 10, 4], "6/1/1/41"}, {Subsuperscript["N", 32, 4], 
  Subsuperscript["N", 3, 3], "(#60)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 3], 
  Subsuperscript["O", 10, 4], "6/1/1/64"}, {Subsuperscript["N", 33, 4], 
  Subsuperscript["N", 3, 3], "(#61)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 3], 
  Subsuperscript["O", 11, 4], "6/1/1/66"}, {Subsuperscript["N", 34, 4], 
  Subsuperscript["N", 4, 3], "(#52)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 3], 
  Subsuperscript["O", 9, 4], "6/1/1/82"}, {Subsuperscript["N", 35, 4], 
  Subsuperscript["N", 4, 3], "(#60)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 3], 
  Subsuperscript["O", 10, 4], "6/1/1/83"}, {Subsuperscript["N", 36, 4], 
  Subsuperscript["N", 4, 3], "(#56)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 3], Subsuperscript["O", 10, 4], "6/1/1/81"}, 
 {Subsuperscript["N", 37, 4], Subsuperscript["N", 4, 3], "(#62)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] 
   Subscript["Z", 4], Subsuperscript["C", 2, 3], Subsuperscript["O", 11, 4], 
  "6/1/1/45"}, {Subsuperscript["N", 38, 4], Subsuperscript["O", 6, 3], 
  "(#62)", Subscript["C", 2], "Z" \[CirclePlus] 
   Subscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 3], Subsuperscript["O", 14, 4], "6/1/1/49"}, 
 {Subsuperscript["N", 39, 4], Subsuperscript["O", 6, 3], "(#61)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Subsuperscript["C", 2, 3], Subsuperscript["O", 14, 4], "6/1/1/92"}, 
 {Subsuperscript["N", 40, 4], Subsuperscript["O", 6, 3], "(#122)", 
  Subscript["C", 4], "Z" \[CirclePlus] Subscript["Z", 2], Subscript["D", 4], 
  Subsuperscript["O", 15, 4], "12/3/10/5"}, {Subsuperscript["N", 41, 4], 
  Subsuperscript["O", 6, 3], "(#114)", Subscript["C", 4], 
  "Z" \[CirclePlus] Subscript["Z", 4], Subscript["D", 4], 
  Subsuperscript["O", 17, 4], "12/3/4/6"}, {Subsuperscript["N", 42, 4], 
  Subsuperscript["O", 2, 3], "(#176)", Subscript["C", 6], 
  "Z" \[CirclePlus] Subscript["Z", 2], 
  Row[{Subscript["C", 2], "\[Times]", Subscript["C", 6]}], 
  Subsuperscript["O", 8, 4], "15/1/1/10"}, {Subsuperscript["N", 43, 4], 
  Subsuperscript["O", 6, 3], "(#205)", Subscript["C", 6], "Z", 
  Row[{Subscript["C", 2], "\[Times]", Subscript["A", 4]}], 
  Subsuperscript["O", 26, 4], "25/1/1/10"}, {Subsuperscript["N", 44, 4], 
  Subsuperscript["N", 44, 4], Subsuperscript["N", 44, 4], Subscript["C", 1], 
  Subscript["Z", 2] \[CirclePlus] Subsuperscript["Z", 4, 2], 
  Subsuperscript["C", 2, 2], Subsuperscript["O", 2, 4], "4/3/1/6"}, 
 {Subsuperscript["N", 45, 4], Subsuperscript["N", 45, 4], 
  Subsuperscript["N", 45, 4], Subscript["C", 1], 
  Subsuperscript["Z", 2, 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 3], Subsuperscript["O", 9, 4], "6/2/1/50"}, 
 {Subsuperscript["N", 46, 4], Subsuperscript["N", 46, 4], 
  Subsuperscript["N", 46, 4], Subscript["C", 1], 
  Subsuperscript["Z", 2, 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 3], Subsuperscript["O", 10, 4], "6/2/1/27"}, 
 {Subsuperscript["N", 47, 4], Subsuperscript["N", 47, 4], 
  Subsuperscript["N", 47, 4], Subscript["C", 1], Subsuperscript["Z", 4, 2], 
  Subscript["D", 4], Subsuperscript["O", 12, 4], "12/4/3/11"}}
