{{1, Subsuperscript["O", 1, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 1], {{1, 0}, {0, 1}}}, 
 {2, Subsuperscript["O", 2, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 2], {{-1, 0}, {0, -1}}}, 
 {3, Subsuperscript["O", 3, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 3], {{0, -1}, {1, -1}}}, 
 {4, Subsuperscript["O", 4, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 4], {{0, -1}, {1, 0}}}, 
 {5, Subsuperscript["O", 5, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 6], {{1, -1}, {1, 0}}}, 
 {6, Subsuperscript["N", 1, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 2], {{1, 0}, {0, -1}}}, 
 {7, Subsuperscript["N", 2, 3], Row[{Superscript["T", 2], "|", 
    Superscript["S", 1]}], Subscript["C", 2], {{0, 1}, {1, 0}}}}
