{{Subsuperscript["O", 1, 4], Superscript["E", 0], Superscript["E", 0], 
  Subscript["C", 1], Superscript["Z", 4], Subscript["C", 1], "1/1/1/1"}, 
 {Subsuperscript["O", 2, 4], Superscript["T", 2], "2222", Subscript["C", 2], 
  Superscript["Z", 2] \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Subscript["C", 2], "3/1/1/2"}, {Subsuperscript["O", 3, 4], 
  Superscript["T", 2], "2222", Subsuperscript["C", 2, 2], 
  Superscript["Z", 2] \[CirclePlus] Subscript["Z", 2], Subscript["C", 2], 
  "3/1/2/2"}, {Subsuperscript["O", 4, 4], Superscript["T", 2], "333", 
  Subscript["C", 3], Superscript["Z", 2] \[CirclePlus] Subscript["Z", 3], 
  Subscript["C", 3], "8/1/2/2"}, {Subsuperscript["O", 5, 4], 
  Superscript["T", 2], "333", Subsuperscript["C", 3, 2], Superscript["Z", 2], 
  Subscript["C", 3], "8/1/1/2"}, {Subsuperscript["O", 6, 4], 
  Superscript["T", 2], "442", Subscript["C", 4], 
  Superscript["Z", 2] \[CirclePlus] Subscript["Z", 2], Subscript["C", 4], 
  "7/2/1/2"}, {Subsuperscript["O", 7, 4], Superscript["T", 2], "442", 
  Row[{Subscript["C", 4], "\[Times]", Subscript["C", 2]}], 
  Superscript["Z", 2], Subscript["C", 4], "7/2/2/2"}, 
 {Subsuperscript["O", 8, 4], Superscript["T", 2], "632", Subscript["C", 6], 
  Superscript["Z", 2], Subscript["C", 6], "9/1/1/2"}, 
 {Subsuperscript["O", 9, 4], Subsuperscript["O", 2, 3], "(#17)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 3], 
  Subsuperscript["C", 2, 2], "5/1/2/7"}, {Subsuperscript["O", 10, 4], 
  Subsuperscript["O", 2, 3], "(#18)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 2], "5/1/2/8"}, {Subsuperscript["O", 11, 4], 
  Subsuperscript["O", 2, 3], Subsuperscript["O", 6, 3], Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 2], "5/1/2/10"}, {Subsuperscript["O", 12, 4], 
  Subsuperscript["O", 2, 3], "(#20)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 2], 
  "5/1/3/6"}, {Subsuperscript["O", 13, 4], Subsuperscript["O", 2, 3], 
  Subsuperscript["O", 6, 3], Subscript["C", 4], 
  "Z" \[CirclePlus] Subscript["Z", 4], Subsuperscript["C", 2, 2], 
  "5/1/10/4"}, {Subsuperscript["O", 14, 4], Subsuperscript["O", 6, 3], 
  Subsuperscript["O", 6, 3], Subscript["C", 1], 
  "Z" \[CirclePlus] Subsuperscript["Z", 4, 2], Subsuperscript["C", 2, 2], 
  "5/1/2/9"}, {Subsuperscript["O", 15, 4], Subsuperscript["O", 6, 3], 
  "(#24)", Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Subsuperscript["C", 2, 2], "5/1/7/4"}, {Subsuperscript["O", 16, 4], 
  Subsuperscript["O", 6, 3], "(#20)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], Subsuperscript["C", 2, 2], 
  "5/1/6/6"}, {Subsuperscript["O", 17, 4], Subsuperscript["O", 6, 3], 
  "(#18)", Subscript["C", 2], "Z" \[CirclePlus] 
   Subscript["Z", 2] \[CirclePlus] Subscript["Z", 4], 
  Subsuperscript["C", 2, 2], "5/1/4/6"}, {Subsuperscript["O", 18, 4], 
  Subsuperscript["O", 3, 3], "(#152)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2] \[CirclePlus] Subscript["Z", 3], 
  Subscript["D", 3], "14/3/5/4"}, {Subsuperscript["O", 19, 4], 
  Subsuperscript["O", 3, 3], "(#151)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2], Subscript["D", 3], "14/3/6/4"}, 
 {Subsuperscript["O", 20, 4], Subsuperscript["O", 3, 3], "(#152)", 
  Subscript["C", 6], "Z" \[CirclePlus] Subscript["Z", 2], Subscript["D", 3], 
  "14/3/1/4"}, {Subsuperscript["O", 21, 4], Subsuperscript["O", 4, 3], 
  "(#91)", Subscript["C", 2], "Z" \[CirclePlus] Subsuperscript["Z", 2, 2], 
  Subscript["D", 4], "13/4/1/14"}, {Subsuperscript["O", 22, 4], 
  Subsuperscript["O", 4, 3], "(#92)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 4], Subscript["D", 4], "13/4/1/20"}, 
 {Subsuperscript["O", 23, 4], Subsuperscript["O", 6, 3], "(#92)", 
  Subscript["C", 2], "Z" \[CirclePlus] Subscript["Z", 4], Subscript["D", 4], 
  "13/4/1/23"}, {Subsuperscript["O", 24, 4], Subsuperscript["O", 6, 3], 
  "(#92)", Subscript["C", 4], "Z" \[CirclePlus] Subscript["Z", 2], 
  Subscript["D", 4], "13/4/4/11"}, {Subsuperscript["O", 25, 4], 
  Subsuperscript["O", 5, 3], "(#178)", Subscript["C", 2], 
  "Z" \[CirclePlus] Subscript["Z", 2], Subscript["D", 6], "15/4/1/10"}, 
 {Subsuperscript["O", 26, 4], Subsuperscript["O", 6, 3], "(#198)", 
  Subscript["C", 3], "Z", Subscript["A", 4], "24/1/2/4"}, 
 {Subsuperscript["O", 27, 4], Subsuperscript["O", 6, 3], "(#199)", 
  Subscript["C", 6], "Z", Subscript["A", 4], "24/1/4/4"}}
